### ISSUE TITLE
create_pmap function not working as expected.

### ISSUE THREAD

**Issue by maxisme** [claesenm/optunity#88]
I am running the:

```
pmap = optunity.parallel.create_pmap(24)
optimal_configuration, info, _ = optunity.maximize_structured(performance,
                                                              search_space=search,
                                                              pmap=pmap,
                                                              num_evals=500)
```
where the `search_space` has 5 algorithms.

As you know an `SVM` takes a lot longer to model than a `k-nn` this means that at first all 24 cores are used but they appear to then wait for the SVM to finish where only one core is used for the SVM when I would want all the cores to be then be split among the last SVM models. How can I do that?

**Comment by maxisme** [comment]
https://stackoverflow.com/questions/44115685/how-to-properly-use-a-process-map-function

**Comment by claesenm** [comment]
Unfortunately, because Optunity is entirely agnostic to the objective
function, we do not have features that enable redirecting computational
resources. Currently each particle swarm iteration is synchronous, and
hence takes as long as the slowest particle (candidate solution) - this is
where your problem is coming from.

One of our future envisioned features include an asynchronous particle
swarm solver, where each particle (candidate solution) is evaluated
independently of the swarm. Your problem would be fixed by asynchronous
PSO, though I can't give a time estimate for this feature right now
(several months at least).

An alternative fix would be to increase the size of the PSO swarm (i.e.,
more particles), which reduces the amount of synchronous batch iterations,
so you will likely achieve better utilisation of your cores.

2017-05-22 16:37 GMT+02:00 Maximilian Mitchell <notifications@github.com>:
